version: '3'
services:
  proxy:
    depends_on:
      - docker-nginx
    image: webapp/proxy
    build: ./proxy 
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./keys/:/keys/:ro
  
  docker-nginx:
     image: nginx:alpine 
